---
title: "01_Quant_plots"
author: "Hannah Koenker"
date: "12/3/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse)
library(maptools)
library(maps)
library(broom)
library(readxl)
library(janitor)
library(spData)
library(sf)
# library(MazamaSpatialUtils)
```

```{r read}
npp <- read_csv("data/mean_npp.csv") %>% 
  clean_names()
```

```{r map}
africa = world %>%
  filter(continent == "Africa",!is.na(iso_a2)) %>%
  left_join(worldbank_df, by = "iso_a2") %>%
  left_join(npp, by = "iso_a2") %>%
  st_transform("+proj=aea +lat_1=20 +lat_2=-23 +lat_0=0 +lon_0=25") %>%
  mutate(
    npp = percpop - 6,
    npp = ceiling(npp)
  )
# plot(africa)

  # cut_width(npp, width = 1, center = 0.5))
# round_half_up(npp),
#     npp = cut(npp, breaks = c(0, 16, 17, 18, 19, 20, 21, 22, 23))
```


``` {r MapQuant1}
ggplot() +
  geom_sf(data = africa,
          aes(fill = as.factor(npp)),
          color = "white",
          size = 0.5) +
  theme_void() +
  scale_fill_brewer(
    palette = "Spectral",
    na.value = "WhiteSmoke",
    direction = -1
  ) +
  coord_sf() +
  labs(fill = "Population multiplier (percent)",
       title = "Recommended population-based quantifier for annual continuous distribution; \nindependent of ANC/EPI ITN distribution") +
  theme(plot.margin = grid::unit(c(0, 0, 0, 0), "null"))

ggsave("quant_scen2_map.png")

# ,    guide = guide_legend(reverse = TRUE) -- reverses the legend order, but not the colors
```

``` {r MapQuant2}
ggplot() +
  geom_sf(
    data = africa,
    aes(fill = percpop),
    color = "white",
    size = 0.5
  ) +
  theme_void() +
  scale_fill_gradient(low = "#56B1F7", high = "#132B43",na.value = "WhiteSmoke") +
  coord_sf() +
  labs(fill = "Population multiplier (percent)",
       title = "Recommended quantifier for annual continuous distribution") +
  theme(plot.margin = grid::unit(c(0, 0, 0, 0), "null"))

ggsave("quant_scen2_map.png")

```{r make_sf}
# crs_africa <-  st_crs(africa)

 #   labels = c(
  #     "0-1",
  #     "1-2",
  #     "2-3",
  #     "3-4",
  #     "4-5",
  #     "5-6",
  #     "results pending or unpublished"
  #   )
  # ) +
```
```

