---
title: "99_Old_Code"
author: "Hannah Koenker"
date: "`r Sys.Date()`"
output: html_document
---

# Leftover code not used in the quant_pword.Rmd file.

```{r}
# tnets %>% 
#   ggplot(aes(y=iso_a2, x=s2vs3, fill=scenario_3<10)) +
#   geom_col()
#          
# totalnets %>% 
#   ggplot(aes(y=totalnets, x=scenario, fill=scenario))+
#   geom_col() +
#   facet_wrap(~iso_a2)

## get a new geofacet, not sure why mine is not working now....fixed as long as I exclude Eritrea :(
# ssa_grid2 <- read_excel("data/ssa_grid2.xlsx") %>% 
#   # filter(code!="NAM" & code!="BW" & code!="CV" & code!="ST") %>% 
#   rename(iso2=code) %>% 
#   mutate(iso3=countrycode(iso2, origin="iso2c", destination="iso3c"),
#          code=iso3) %>% 
#   select(name, code, row, col)



## facet by lifespan just adds up all the 1s for scenario 2, all pct values for other scenarios...doesn't reflect anything useful.
# scenpct %>% 
#   ggplot(aes(y=pct, x=scenario, fill=scenario))+
#   geom_col() +
#   facet_wrap(~lifespan)

## testing the process for shifting the origin to 0 so that bars go up and down vis a vis Full Scale CD
# scenpct %>% 
#   filter(name=="Zambia") %>% 
#   ggplot(aes(x=scenario, y=pct-1, fill=scenario)) +
#   geom_col() +
#   geom_hline(yintercept=0) +
#   scale_y_continuous(name = "Percent",
#                      breaks = seq(-1, 1, 0.2),
#                      labels = seq(-1, 1, 0.2))
  
# ggsave("figs/Fig_totnetsmap.png")

# ggarrange(asp,mapscen, nrow=, ncol=1, widths=c(1,3), heights=c(1,3))  
# ggarrange(mapscen, asp, nrow=2, ncol=1, widths=c(3,1), heights=c(3,1), labels="AUTO", align="h")

## Two-row patchwork to combine the graphs
# mapscen/asp + 
#   plot_annotation(tag_levels = 'A') + 
#   plot_layout(heights = c(3, 1))



```

```{r}
# ggarrange(dmmap,
#           ggarrange(decay, npchh, ncol=2, labels=c("B","C")),
#           nrow=2,
#           labels="A")
```

```{r}
# make a table with the target80
# sumtable <- read_excel("data/summary_target80.xlsx") %>% 
#   clean_names() %>% 
#   left_join(qt, by = "iso_a2") %>% 
#   mutate(name = countrycode(iso_a2, origin = "iso2c", destination = "country.name"))

```

```{r gtable80, eval=FALSE, tab.cap="GT Table test"}
## GT table does not appear knitting to Word

# gtable80 <- gt(table80) %>% 
#   tab_header(
#     title = "Recommended quantifiers",
#     subtitle = "To maintain 80% population ITN access") %>% 
#    tab_spanner(
#     label = "Continuous Distribution",
#     columns = c(scenario_2, scenario_3)
#   ) %>%
#   tab_spanner(
#     label = "Mass Campaign",
#     columns = c(scenario_4, scenario_5)
#   ) %>% 
#    cols_label(
#     scenario_1 = html("Campaign + routine"),
#     scenario_2 = html("Full-scale continuous + routine"),
#     scenario_3 = html("Campaign + routine + continuous between campaigns"),
#     scenario_4 = html("3-yearly campaigns"),
#      scenario_5 = html("2-yearly campaigns")
#   ) %>% 
#   fmt_missing(
#     columns = everything(),
#     missing_text = ""
#   )
# gtable80
```


```{r kabletable80, eval=FALSE, tab.cap = "Summary of recommended quantifiers for scenarios, to maintain ITN access at or above 80%"}
# table80 %>% 
#   select(-scenario_1) %>% 
#   kable(col.names = c("Country","Full-scale continuous + routine","Campaign + routine + continuous between campaigns","3-yearly campaigns","2-yearly campaigns")) %>%
#   kable_paper(full_width = F) %>% 
#   add_header_above(c(" " = 1, "Continuous Distribution" = 2, "Mass Campaign" = 2))
```
